/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PremiumfeaturesRouteImport } from './routes/premiumfeatures'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as HousesRouteImport } from './routes/houses'
import { Route as HighscoresRouteImport } from './routes/highscores'
import { Route as GuildsRouteImport } from './routes/guilds'
import { Route as FoundguildRouteImport } from './routes/foundguild'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CreaturesRouteImport } from './routes/creatures'
import { Route as CreateaccountRouteImport } from './routes/createaccount'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountManageRouteImport } from './routes/account.manage'
import { Route as AccountCreatecharacterRouteImport } from './routes/account.createcharacter'
import { Route as AccountChangepasswordRouteImport } from './routes/account.changepassword'
import { Route as AccountChangemainRouteImport } from './routes/account.changemain'
import { Route as AccountChangeemailRouteImport } from './routes/account.changeemail'
import { Route as AccountAuthenticationRouteImport } from './routes/account.authentication'
import { Route as AccountCharacterEditRouteImport } from './routes/account.character.edit'
import { Route as AccountCharacterDeleteRouteImport } from './routes/account.character.delete'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumfeaturesRoute = PremiumfeaturesRouteImport.update({
  id: '/premiumfeatures',
  path: '/premiumfeatures',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesRoute = HousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const HighscoresRoute = HighscoresRouteImport.update({
  id: '/highscores',
  path: '/highscores',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsRoute = GuildsRouteImport.update({
  id: '/guilds',
  path: '/guilds',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundguildRoute = FoundguildRouteImport.update({
  id: '/foundguild',
  path: '/foundguild',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CreaturesRoute = CreaturesRouteImport.update({
  id: '/creatures',
  path: '/creatures',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateaccountRoute = CreateaccountRouteImport.update({
  id: '/createaccount',
  path: '/createaccount',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountManageRoute = AccountManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCreatecharacterRoute = AccountCreatecharacterRouteImport.update({
  id: '/createcharacter',
  path: '/createcharacter',
  getParentRoute: () => AccountRoute,
} as any)
const AccountChangepasswordRoute = AccountChangepasswordRouteImport.update({
  id: '/changepassword',
  path: '/changepassword',
  getParentRoute: () => AccountRoute,
} as any)
const AccountChangemainRoute = AccountChangemainRouteImport.update({
  id: '/changemain',
  path: '/changemain',
  getParentRoute: () => AccountRoute,
} as any)
const AccountChangeemailRoute = AccountChangeemailRouteImport.update({
  id: '/changeemail',
  path: '/changeemail',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAuthenticationRoute = AccountAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCharacterEditRoute = AccountCharacterEditRouteImport.update({
  id: '/character/edit',
  path: '/character/edit',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCharacterDeleteRoute = AccountCharacterDeleteRouteImport.update({
  id: '/character/delete',
  path: '/character/delete',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/characters': typeof CharactersRoute
  '/cookies': typeof CookiesRoute
  '/createaccount': typeof CreateaccountRoute
  '/creatures': typeof CreaturesRoute
  '/downloads': typeof DownloadsRoute
  '/foundguild': typeof FoundguildRoute
  '/guilds': typeof GuildsRoute
  '/highscores': typeof HighscoresRoute
  '/houses': typeof HousesRoute
  '/items': typeof ItemsRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/premiumfeatures': typeof PremiumfeaturesRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/account/authentication': typeof AccountAuthenticationRoute
  '/account/changeemail': typeof AccountChangeemailRoute
  '/account/changemain': typeof AccountChangemainRoute
  '/account/changepassword': typeof AccountChangepasswordRoute
  '/account/createcharacter': typeof AccountCreatecharacterRoute
  '/account/manage': typeof AccountManageRoute
  '/account/': typeof AccountIndexRoute
  '/account/character/delete': typeof AccountCharacterDeleteRoute
  '/account/character/edit': typeof AccountCharacterEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/cookies': typeof CookiesRoute
  '/createaccount': typeof CreateaccountRoute
  '/creatures': typeof CreaturesRoute
  '/downloads': typeof DownloadsRoute
  '/foundguild': typeof FoundguildRoute
  '/guilds': typeof GuildsRoute
  '/highscores': typeof HighscoresRoute
  '/houses': typeof HousesRoute
  '/items': typeof ItemsRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/premiumfeatures': typeof PremiumfeaturesRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/account/authentication': typeof AccountAuthenticationRoute
  '/account/changeemail': typeof AccountChangeemailRoute
  '/account/changemain': typeof AccountChangemainRoute
  '/account/changepassword': typeof AccountChangepasswordRoute
  '/account/createcharacter': typeof AccountCreatecharacterRoute
  '/account/manage': typeof AccountManageRoute
  '/account': typeof AccountIndexRoute
  '/account/character/delete': typeof AccountCharacterDeleteRoute
  '/account/character/edit': typeof AccountCharacterEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/characters': typeof CharactersRoute
  '/cookies': typeof CookiesRoute
  '/createaccount': typeof CreateaccountRoute
  '/creatures': typeof CreaturesRoute
  '/downloads': typeof DownloadsRoute
  '/foundguild': typeof FoundguildRoute
  '/guilds': typeof GuildsRoute
  '/highscores': typeof HighscoresRoute
  '/houses': typeof HousesRoute
  '/items': typeof ItemsRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/premiumfeatures': typeof PremiumfeaturesRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/account/authentication': typeof AccountAuthenticationRoute
  '/account/changeemail': typeof AccountChangeemailRoute
  '/account/changemain': typeof AccountChangemainRoute
  '/account/changepassword': typeof AccountChangepasswordRoute
  '/account/createcharacter': typeof AccountCreatecharacterRoute
  '/account/manage': typeof AccountManageRoute
  '/account/': typeof AccountIndexRoute
  '/account/character/delete': typeof AccountCharacterDeleteRoute
  '/account/character/edit': typeof AccountCharacterEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/characters'
    | '/cookies'
    | '/createaccount'
    | '/creatures'
    | '/downloads'
    | '/foundguild'
    | '/guilds'
    | '/highscores'
    | '/houses'
    | '/items'
    | '/legal'
    | '/login'
    | '/payment'
    | '/premiumfeatures'
    | '/privacy'
    | '/rules'
    | '/team'
    | '/terms'
    | '/account/authentication'
    | '/account/changeemail'
    | '/account/changemain'
    | '/account/changepassword'
    | '/account/createcharacter'
    | '/account/manage'
    | '/account/'
    | '/account/character/delete'
    | '/account/character/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/cookies'
    | '/createaccount'
    | '/creatures'
    | '/downloads'
    | '/foundguild'
    | '/guilds'
    | '/highscores'
    | '/houses'
    | '/items'
    | '/legal'
    | '/login'
    | '/payment'
    | '/premiumfeatures'
    | '/privacy'
    | '/rules'
    | '/team'
    | '/terms'
    | '/account/authentication'
    | '/account/changeemail'
    | '/account/changemain'
    | '/account/changepassword'
    | '/account/createcharacter'
    | '/account/manage'
    | '/account'
    | '/account/character/delete'
    | '/account/character/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/characters'
    | '/cookies'
    | '/createaccount'
    | '/creatures'
    | '/downloads'
    | '/foundguild'
    | '/guilds'
    | '/highscores'
    | '/houses'
    | '/items'
    | '/legal'
    | '/login'
    | '/payment'
    | '/premiumfeatures'
    | '/privacy'
    | '/rules'
    | '/team'
    | '/terms'
    | '/account/authentication'
    | '/account/changeemail'
    | '/account/changemain'
    | '/account/changepassword'
    | '/account/createcharacter'
    | '/account/manage'
    | '/account/'
    | '/account/character/delete'
    | '/account/character/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  CharactersRoute: typeof CharactersRoute
  CookiesRoute: typeof CookiesRoute
  CreateaccountRoute: typeof CreateaccountRoute
  CreaturesRoute: typeof CreaturesRoute
  DownloadsRoute: typeof DownloadsRoute
  FoundguildRoute: typeof FoundguildRoute
  GuildsRoute: typeof GuildsRoute
  HighscoresRoute: typeof HighscoresRoute
  HousesRoute: typeof HousesRoute
  ItemsRoute: typeof ItemsRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  PremiumfeaturesRoute: typeof PremiumfeaturesRoute
  PrivacyRoute: typeof PrivacyRoute
  RulesRoute: typeof RulesRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premiumfeatures': {
      id: '/premiumfeatures'
      path: '/premiumfeatures'
      fullPath: '/premiumfeatures'
      preLoaderRoute: typeof PremiumfeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highscores': {
      id: '/highscores'
      path: '/highscores'
      fullPath: '/highscores'
      preLoaderRoute: typeof HighscoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds': {
      id: '/guilds'
      path: '/guilds'
      fullPath: '/guilds'
      preLoaderRoute: typeof GuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundguild': {
      id: '/foundguild'
      path: '/foundguild'
      fullPath: '/foundguild'
      preLoaderRoute: typeof FoundguildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatures': {
      id: '/creatures'
      path: '/creatures'
      fullPath: '/creatures'
      preLoaderRoute: typeof CreaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createaccount': {
      id: '/createaccount'
      path: '/createaccount'
      fullPath: '/createaccount'
      preLoaderRoute: typeof CreateaccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/manage': {
      id: '/account/manage'
      path: '/manage'
      fullPath: '/account/manage'
      preLoaderRoute: typeof AccountManageRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/createcharacter': {
      id: '/account/createcharacter'
      path: '/createcharacter'
      fullPath: '/account/createcharacter'
      preLoaderRoute: typeof AccountCreatecharacterRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/changepassword': {
      id: '/account/changepassword'
      path: '/changepassword'
      fullPath: '/account/changepassword'
      preLoaderRoute: typeof AccountChangepasswordRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/changemain': {
      id: '/account/changemain'
      path: '/changemain'
      fullPath: '/account/changemain'
      preLoaderRoute: typeof AccountChangemainRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/changeemail': {
      id: '/account/changeemail'
      path: '/changeemail'
      fullPath: '/account/changeemail'
      preLoaderRoute: typeof AccountChangeemailRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/authentication': {
      id: '/account/authentication'
      path: '/authentication'
      fullPath: '/account/authentication'
      preLoaderRoute: typeof AccountAuthenticationRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/character/edit': {
      id: '/account/character/edit'
      path: '/character/edit'
      fullPath: '/account/character/edit'
      preLoaderRoute: typeof AccountCharacterEditRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/character/delete': {
      id: '/account/character/delete'
      path: '/character/delete'
      fullPath: '/account/character/delete'
      preLoaderRoute: typeof AccountCharacterDeleteRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAuthenticationRoute: typeof AccountAuthenticationRoute
  AccountChangeemailRoute: typeof AccountChangeemailRoute
  AccountChangemainRoute: typeof AccountChangemainRoute
  AccountChangepasswordRoute: typeof AccountChangepasswordRoute
  AccountCreatecharacterRoute: typeof AccountCreatecharacterRoute
  AccountManageRoute: typeof AccountManageRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountCharacterDeleteRoute: typeof AccountCharacterDeleteRoute
  AccountCharacterEditRoute: typeof AccountCharacterEditRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAuthenticationRoute: AccountAuthenticationRoute,
  AccountChangeemailRoute: AccountChangeemailRoute,
  AccountChangemainRoute: AccountChangemainRoute,
  AccountChangepasswordRoute: AccountChangepasswordRoute,
  AccountCreatecharacterRoute: AccountCreatecharacterRoute,
  AccountManageRoute: AccountManageRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountCharacterDeleteRoute: AccountCharacterDeleteRoute,
  AccountCharacterEditRoute: AccountCharacterEditRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  CharactersRoute: CharactersRoute,
  CookiesRoute: CookiesRoute,
  CreateaccountRoute: CreateaccountRoute,
  CreaturesRoute: CreaturesRoute,
  DownloadsRoute: DownloadsRoute,
  FoundguildRoute: FoundguildRoute,
  GuildsRoute: GuildsRoute,
  HighscoresRoute: HighscoresRoute,
  HousesRoute: HousesRoute,
  ItemsRoute: ItemsRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  PremiumfeaturesRoute: PremiumfeaturesRoute,
  PrivacyRoute: PrivacyRoute,
  RulesRoute: RulesRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
